export const ADD_TO_MEAL = "ADD_TO_MEAL";
export const UPDATE_FOODS_RESULTS = "UPDATE_FOODS_RESULTS";
export const UPDATE_SEARCH_CRITERIA = "UPDATE_SEARCH_CRITERIA";

export const UPDATE_TIMELINE = "UPDATE_TIMELINE";
