export const UPDATE_FOODS_RESULTS = "UPDATE_FOODS_RESULTS";
export const UPDATE_SEARCH_CRITERIA = "UPDATE_SEARCH_CRITERIA";

export const UPDATE_TIMELINE = "UPDATE_TIMELINE";

export const ADD_TO_MEAL = 'ADD_TO_MEAL';
export const ADD_MULTIPLE_TO_MEAL = 'ADD_MULTIPLE_TO_MEAL';
export const REMOVE_FROM_MEAL = 'REMOVE_FROM_MEAL';
export const UPDATE_MEAL_QUANTITY = 'UPDATE_MEAL_QUANTITY';
export const CLEAR_MEAL = 'CLEAR_MEAL';
export const TOGGLE_MEAL = 'TOGGLE_MEAL';